### ISSUE TITLE
Token not accepted

### ISSUE THREAD

**Issue by hansvveen** [agladky/todoist-overdue-alfred#1]
I love to run this workflow. However following the instructions I get the message 'token is not specified. set another in workflow'. I added the value of my todoist api in the value field. Under name I filled in 'Token' and I did not mark the 'Don't Export' checkbox.

Appreciate your tips!

**Comment by agladky** [comment]
@hansvveen Thanks for your message.

I think I got the problem. You need to change your variable name from “Token” to “token”.

In the Alfred, variables are case sensitive. I didn't find a fast way to ignore this, so I updated a instruction in my workflow. [Commit.](https://github.com/agladky/todoist-overdue-alfred/commit/18783949f57e3c10cd31959a6bda3209b6e46f0a)

Let me know if it helps!

**Comment by hansvveen** [comment]
Thanks for your replky @agladky 

changed to undercast. But still the same error. See images attached.

<img width="1102" alt="screen shot 2018-01-31 at 13 49 58" src="https://user-images.githubusercontent.com/35993167/35623991-d6176c96-068d-11e8-849e-e288710d4ffe.png">
<img width="353" alt="screen shot 2018-01-31 at 13 51 53" src="https://user-images.githubusercontent.com/35993167/35624010-e9df0554-068d-11e8-896e-61684c2a4c44.png">

**Comment by agladky** [comment]
@hansvveen Oh, I see. My workflow took a token from “Arg and Vars” utilities. Right steps in my screenshot.

But it's a good idea, to use “Workflow Environment Variables” for storing. I'll think about it, thanks!

<img width="1397" alt="screenshot 2018-01-31 16 14 45" src="https://user-images.githubusercontent.com/9007536/35625494-9cd1763c-06a3-11e8-81f2-80b25e550899.png">

**Comment by hansvveen** [comment]
Yes! Works like a charm. Thanks a lot!
